"""Add Firm model

Revision ID: 371957149141
Revises: 208df79cfd4e
Create Date: 2026-05-13 15:06:27.304932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371957149141'
down_revision: Union[str, None] = '208df79cfd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_owner_id'), 'firm', ['owner_id'], unique=False)
    op.add_column('employee', sa.Column('firm_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_employee_firm_id'), 'employee', ['firm_id'], unique=False)
    op.create_foreign_key(None, 'employee', 'firm', ['firm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_index(op.f('ix_employee_firm_id'), table_name='employee')
    op.drop_column('employee', 'firm_id')
    op.drop_index(op.f('ix_firm_owner_id'), table_name='firm')
    op.drop_table('firm')
    # ### end Alembic commands ###
